#include "localization.h"
#include "../config/app_settings.h"

#include <cstring>
#include <cstdio>
#include <unordered_map>
#include <string_view>

namespace Loc {
namespace {

    struct Pack {
        const char* pt;
        const char* en;
        const char* de;
        const char* es;
        const char* fr;
        const char* it;
    };

    const std::unordered_map<std::string_view, Pack> kTable = {
        {"nav.title", {"NAVEGAÇÃO", "NAVIGATION", "NAVIGATION", "NAVEGACION", "NAVIGATION", "NAVIGAZIONE"}},
        {"nav.visuals", {"Visuais", "Visuals", "Visuals", "Visuales", "Visuels", "Visuali"}},
        {"nav.aim", {"Mira", "Aim", "Aim", "Punteria", "Visee", "Mira"}},
        {"nav.vehicles", {"Veículos", "Vehicles", "Fahrzeuge", "Vehiculos", "Vehicules", "Veicoli"}},
        {"nav.friends", {"Amigos", "Friends", "Freunde", "Amigos", "Amis", "Amici"}},
        {"nav.configs", {"Definições", "Configs", "Einstellungen", "Ajustes", "Reglages", "Impostazioni"}},
        {"nav.save", {"Guardar", "Save/Load", "Speichern/Laden", "Guardar/Cargar", "Sauver/Charger", "Salva/Carica"}},
        {"nav.status", {"Estado", "Status", "Status", "Status", "Status", "Status"}},
        {"nav.world", {"Mundo", "World", "World", "World", "World", "World"}},
        {"nav.players", {"Jogadores", "Players", "Players", "Players", "Players", "Players"}},
        {"nav.radar", {"Radar", "Radar", "Radar", "Radar", "Radar", "Radar"}},
        {"nav.misc", {"Diversos", "Misc", "Misc", "Misc", "Misc", "Misc"}},
        {"nav.debug", {"Diagnóstico", "Diagnostics", "Diagnostics", "Diagnostics", "Diagnostics", "Diagnostics"}},
        {"nav.trigger", {"Disparo automático", "Trigger", "Trigger", "Trigger", "Trigger", "Trigger"}},
        {"nav.player_esp", {"ESP de jogadores", "Player ESP", "Player ESP", "Player ESP", "Player ESP", "Player ESP"}},
        {"nav.world_esp", {"ESP do mundo", "World ESP", "World ESP", "World ESP", "World ESP", "World ESP"}},
        {"nav.webradar", {"Web Radar", "Web Radar", "Web Radar", "Web Radar", "Web Radar", "Web Radar"}},
        {"nav.interface", {"Interface", "Interface", "Interface", "Interface", "Interface", "Interface"}},
        {"nav.macros", {"Macros", "Macros", "Macros", "Macros", "Macros", "Macros"}},

        {"launcher.home", {"Início", "Home", "Home", "Home", "Home", "Home"}},
        {"launcher.library", {"Biblioteca", "Library", "Library", "Library", "Library", "Library"}},
        {"launcher.updates", {"Atualizações", "Updates", "Updates", "Updates", "Updates", "Updates"}},
        {"launcher.diagnostics", {"Diagnóstico", "Diagnostics", "Diagnostics", "Diagnostics", "Diagnostics", "Diagnostics"}},
        {"launcher.settings", {"Definições", "Settings", "Settings", "Settings", "Settings", "Settings"}},
        {"launcher.account", {"Conta", "Account", "Account", "Account", "Account", "Account"}},
        {"launcher.profile", {"Perfil", "Profile", "Profile", "Profile", "Profile", "Profile"}},
        {"launcher.logout", {"Terminar sessão", "Logout", "Logout", "Logout", "Logout", "Logout"}},
        {"launcher.search_hint", {"Pesquisar jogos…", "Search games…", "Search games…", "Search games…", "Search games…", "Search games…"}},
        {"launcher.games_available", {"%d jogos disponíveis", "%d games available", "%d games available", "%d games available", "%d games available", "%d games available"}},
        {"launcher.filter.all", {"Todos", "All", "All", "All", "All", "All"}},
        {"launcher.filter.installed", {"Instalados", "Installed", "Installed", "Installed", "Installed", "Installed"}},
        {"launcher.filter.running", {"Em execução", "Running", "Running", "Running", "Running", "Running"}},
        {"launcher.filter.ready", {"Prontos", "Ready", "Ready", "Ready", "Ready", "Ready"}},
        {"launcher.status.ready", {"Pronto", "Ready", "Ready", "Ready", "Ready", "Ready"}},
        {"launcher.status.running", {"Em execução", "Running", "Running", "Running", "Running", "Running"}},
        {"launcher.status.not_installed", {"Não instalado", "Not installed", "Not installed", "Not installed", "Not installed", "Not installed"}},
        {"launcher.status.needs_offsets", {"Offsets por validar", "Offsets not validated", "Offsets not validated", "Offsets not validated", "Offsets not validated", "Offsets not validated"}},
        {"launcher.status.device_missing", {"Dispositivo em falta", "Device missing", "Device missing", "Device missing", "Device missing", "Device missing"}},
        {"launcher.status.game_not_found", {"Jogo não encontrado", "Game not found", "Game not found", "Juego no encontrado", "Jeu introuvable", "Gioco non trovato"}},
        {"launcher.status.license_required", {"Licença necessária", "License required", "License required", "Licencia necesaria", "Licence requise", "Licenza necessaria"}},
        {"launcher.status.update_required", {"Atualização necessária", "Update required", "Update required", "Update required", "Update required", "Update required"}},
        {"launcher.status.beta", {"Beta", "Beta", "Beta", "Beta", "Beta", "Beta"}},
        {"launcher.status.coming_soon", {"Em breve", "Coming soon", "Coming soon", "Coming soon", "Coming soon", "Coming soon"}},
        {"launcher.status.launch_failed", {"Falhou ao iniciar", "Launch failed", "Launch failed", "Launch failed", "Launch failed", "Launch failed"}},
        {"launcher.action.how_fix", {"Como corrigir", "How to fix", "How to fix", "How to fix", "How to fix", "How to fix"}},
        {"launcher.action.diagnostics", {"Diagnóstico", "Diagnostics", "Diagnostics", "Diagnostics", "Diagnostics", "Diagnostics"}},
        {"launcher.action.refresh_offsets", {"Atualizar offsets", "Refresh offsets", "Refresh offsets", "Refresh offsets", "Refresh offsets", "Refresh offsets"}},
        {"launcher.action.reset_settings", {"Repor definições", "Reset settings", "Reset settings", "Reset settings", "Reset settings", "Reset settings"}},
        {"launcher.action.open_logs", {"Abrir logs", "Open logs", "Open logs", "Open logs", "Open logs", "Open logs"}},
        {"launcher.action.continue", {"Continuar", "Continue", "Continue", "Continue", "Continue", "Continue"}},
        {"launcher.action.retry", {"Tentar novamente", "Try again", "Try again", "Try again", "Try again", "Try again"}},
        {"launcher.action.add_license", {"Adicionar licença", "Add license", "Add license", "Añadir licencia", "Ajouter une licence", "Aggiungi licenza"}},
        {"launcher.action.pin", {"Fixar", "Pin", "Pin", "Pin", "Pin", "Pin"}},
        {"launcher.action.unpin", {"Desafixar", "Unpin", "Unpin", "Unpin", "Unpin", "Unpin"}},
        {"launcher.toast.offsets_updated", {"Offsets atualizados.", "Offsets updated.", "Offsets updated.", "Offsets updated.", "Offsets updated.", "Offsets updated."}},
        {"launcher.toast.offsets_failed", {"Não foi possível atualizar os offsets.", "Could not refresh offsets.", "Could not refresh offsets.", "Could not refresh offsets.", "Could not refresh offsets.", "Could not refresh offsets."}},
        {"launcher.toast.settings_reset", {"Definições repostas.", "Settings reset.", "Settings reset.", "Settings reset.", "Settings reset.", "Settings reset."}},
        {"launcher.home.subtitle", {"Estado do sistema e atalhos para a tua última sessão.", "System status and shortcuts for your last session.", "System status and shortcuts for your last session.", "System status and shortcuts for your last session.", "System status and shortcuts for your last session.", "System status and shortcuts for your last session."}},
        {"launcher.last_session", {"Última sessão", "Last session", "Last session", "Last session", "Last session", "Last session"}},
        {"launcher.device_status", {"Estado dos dispositivos", "Device status", "Device status", "Device status", "Device status", "Device status"}},
        {"launcher.quick_settings", {"Definições rápidas", "Quick settings", "Quick settings", "Quick settings", "Quick settings", "Quick settings"}},
        {"launcher.continue_last", {"Continuar último jogo", "Continue last game", "Continue last game", "Continue last game", "Continue last game", "Continue last game"}},
        {"launcher.no_history", {"Ainda não existe histórico de sessões.", "No session history yet.", "No session history yet.", "No session history yet.", "No session history yet.", "No session history yet."}},
        {"launcher.dma", {"DMA", "DMA", "DMA", "DMA", "DMA", "DMA"}},
        {"launcher.input", {"Entrada", "Input", "Input", "Input", "Input", "Input"}},
        {"launcher.updates_status", {"Atualizações", "Updates", "Updates", "Updates", "Updates", "Updates"}},
        {"launcher.current", {"Atual", "Current", "Current", "Current", "Current", "Current"}},
        {"launcher.disconnected", {"Desligado", "Disconnected", "Disconnected", "Disconnected", "Disconnected", "Disconnected"}},
        {"launcher.connected", {"Ligado", "Connected", "Connected", "Connected", "Connected", "Connected"}},
        {"launcher.checking", {"A verificar", "Checking", "Checking", "Checking", "Checking", "Checking"}},
        {"launcher.available", {"Disponível", "Available", "Available", "Available", "Available", "Available"}},
        {"launcher.error", {"Erro", "Error", "Error", "Error", "Error", "Error"}},
        {"launcher.none", {"Nenhum", "None", "None", "None", "None", "None"}},
        {"launcher.unknown", {"Desconhecido", "Unknown", "Unknown", "Unknown", "Unknown", "Unknown"}},
        {"launcher.local_account", {"Conta local", "Local account", "Local account", "Local account", "Local account", "Local account"}},
        {"launcher.standby", {"Em espera", "Standby", "Standby", "Standby", "Standby", "Standby"}},
        {"launcher.starting", {"A iniciar…", "Starting…", "Starting…", "Starting…", "Starting…", "Starting…"}},
        {"launcher.click_to_start", {"Clica para iniciar", "Click to start", "Click to start", "Click to start", "Click to start", "Click to start"}},
        {"launcher.running_detected", {"Jogo detetado em execução", "Game detected running", "Game detected running", "Game detected running", "Game detected running", "Game detected running"}},
        {"launcher.start_game", {"Iniciar %s", "Start %s", "Start %s", "Start %s", "Start %s", "Start %s"}},
        {"launcher.toast.starting", {"%s está a iniciar.", "%s is starting.", "%s is starting.", "%s is starting.", "%s is starting.", "%s is starting."}},
        {"launcher.toast.already_running", {"O jogo já foi detetado em execução.", "The game is already detected running.", "The game is already detected running.", "The game is already detected running.", "The game is already detected running.", "The game is already detected running."}},
        {"launcher.empty_title", {"Sem jogos para mostrar", "No games to show", "No games to show", "No games to show", "No games to show", "No games to show"}},
        {"launcher.empty_desc", {"Altera a pesquisa ou os filtros para voltares a ver a biblioteca.", "Change the search or filters to see the library again.", "Change the search or filters to see the library again.", "Change the search or filters to see the library again.", "Change the search or filters to see the library again.", "Change the search or filters to see the library again."}},
        {"launcher.system", {"Sistema", "System", "System", "System", "System", "System"}},
        {"launcher.games", {"Jogos", "Games", "Games", "Games", "Games", "Games"}},
        {"launcher.game", {"Jogo", "Game", "Game", "Game", "Game", "Game"}},
        {"launcher.result", {"Resultado", "Result", "Result", "Result", "Result", "Result"}},
        {"launcher.when", {"Quando", "When", "When", "When", "When", "When"}},
        {"launcher.state", {"Estado", "State", "State", "State", "State", "State"}},
        {"launcher.runtime_local", {"Componente local", "Local runtime", "Local runtime", "Local runtime", "Local runtime", "Local runtime"}},
        {"launcher.offsets", {"Offsets", "Offsets", "Offsets", "Offsets", "Offsets", "Offsets"}},
        {"launcher.installed", {"Instalado", "Installed", "Installed", "Installed", "Installed", "Installed"}},
        {"launcher.missing", {"Em falta", "Missing", "Missing", "Missing", "Missing", "Missing"}},
        {"launcher.attached", {"Anexado", "Attached", "Attached", "Attached", "Attached", "Attached"}},
        {"launcher.not_attached", {"Não anexado", "Not attached", "Not attached", "Not attached", "Not attached", "Not attached"}},
        {"launcher.attention", {"Atenção", "Attention", "Attention", "Attention", "Attention", "Attention"}},
        {"launcher.license_local", {"Licença local", "Local license", "Local license", "Local license", "Local license", "Local license"}},
        {"launcher.diagnostics.subtitle", {"Estado dos componentes locais, dispositivos, atualizações e adaptadores.", "Local runtime, device, update and adapter status.", "Local runtime, device, update and adapter status.", "Local runtime, device, update and adapter status.", "Local runtime, device, update and adapter status.", "Local runtime, device, update and adapter status."}},
        {"launcher.settings.subtitle", {"Preferências globais do centro de controlo e dos menus.", "Global Control Center and menu preferences.", "Global Control Center and menu preferences.", "Global Control Center and menu preferences.", "Global Control Center and menu preferences.", "Global Control Center and menu preferences."}},
        {"launcher.account.subtitle", {"Conta local e licenciamento atual.", "Local account and current licensing.", "Local account and current licensing.", "Local account and current licensing.", "Local account and current licensing.", "Local account and current licensing."}},
        {"launcher.interface", {"Interface", "Interface", "Interface", "Interface", "Interface", "Interface"}},
        {"launcher.scale", {"Escala", "Scale", "Scale", "Scale", "Scale", "Scale"}},
        {"launcher.language", {"Idioma", "Language", "Language", "Language", "Language", "Language"}},
        {"launcher.animation_intensity", {"Intensidade das animações", "Animation intensity", "Animation intensity", "Animation intensity", "Animation intensity", "Animation intensity"}},
        {"launcher.reduce_motion", {"Reduzir movimento", "Reduce motion", "Reduce motion", "Reduce motion", "Reduce motion", "Reduce motion"}},
        {"launcher.auto_performance", {"Desempenho automático", "Auto performance", "Auto performance", "Auto performance", "Auto performance", "Auto performance"}},
        {"launcher.ui_scale", {"Escala da interface", "UI scale", "UI scale", "UI scale", "UI scale", "UI scale"}},
        {"launcher.effect.off", {"Desligado", "Off", "Off", "Off", "Off", "Off"}},
        {"launcher.effect.subtle", {"Subtil", "Subtle", "Subtle", "Subtle", "Subtle", "Subtle"}},
        {"launcher.effect.full", {"Completo", "Full", "Full", "Full", "Full", "Full"}},
        {"launcher.email", {"Email", "Email", "Email", "Email", "Email", "Email"}},
        {"launcher.authentication", {"Autenticação", "Authentication", "Authentication", "Authentication", "Authentication", "Authentication"}},
        {"launcher.local_dpapi", {"Conta local · Windows DPAPI", "Local account · Windows DPAPI", "Local account · Windows DPAPI", "Local account · Windows DPAPI", "Local account · Windows DPAPI", "Local account · Windows DPAPI"}},
        {"launcher.remember_me", {"Guardar dados", "Remember me", "Remember me", "Remember me", "Remember me", "Remember me"}},
        {"launcher.enabled", {"Ativo", "Enabled", "Enabled", "Enabled", "Enabled", "Enabled"}},
        {"launcher.disabled", {"Desativado", "Disabled", "Disabled", "Disabled", "Disabled", "Disabled"}},
        {"launcher.license", {"Licença", "License", "License", "License", "License", "License"}},
        {"launcher.storage", {"Armazenamento", "Storage", "Storage", "Storage", "Storage", "Storage"}},
        {"launcher.unprotected_missing", {"Não protegido / ausente", "Unprotected / missing", "Unprotected / missing", "Unprotected / missing", "Unprotected / missing", "Unprotected / missing"}},
        {"launcher.license_separate", {"A licença local atual mantém-se separada da conta local.", "The current local license remains separate from the local account.", "The current local license remains separate from the local account.", "The current local license remains separate from the local account.", "The current local license remains separate from the local account.", "The current local license remains separate from the local account."}},
        {"launcher.refresh_state", {"Atualizar estado", "Refresh status", "Refresh status", "Refresh status", "Refresh status", "Refresh status"}},
        {"launcher.open_local_folder", {"Abrir pasta local", "Open local folder", "Open local folder", "Open local folder", "Open local folder", "Open local folder"}},
        {"launcher.cancel", {"Cancelar", "Cancel", "Cancel", "Cancel", "Cancel", "Cancel"}},
        {"launcher.close", {"Fechar", "Close", "Close", "Close", "Close", "Close"}},
        {"launcher.reset_title", {"Repor definições?", "Reset settings?", "Reset settings?", "Reset settings?", "Reset settings?", "Reset settings?"}},
        {"launcher.support", {"Discord · Suporte", "Discord · Support", "Discord · Support", "Discord · Support", "Discord · Support", "Discord · Support"}},
        {"launcher.esc_back", {"ESC para voltar", "ESC to go back", "ESC to go back", "ESC to go back", "ESC to go back", "ESC to go back"}},
        {"launcher.performance_auto", {"DESEMPENHO AUTO", "AUTO PERFORMANCE", "AUTO PERFORMANCE", "AUTO PERFORMANCE", "AUTO PERFORMANCE", "AUTO PERFORMANCE"}},
        {"launcher.performance_manual", {"DESEMPENHO MANUAL", "MANUAL PERFORMANCE", "MANUAL PERFORMANCE", "MANUAL PERFORMANCE", "MANUAL PERFORMANCE", "MANUAL PERFORMANCE"}},
        {"launcher.result.none", {"Sem histórico", "No history", "No history", "No history", "No history", "No history"}},
        {"launcher.result.completed", {"Concluída", "Completed", "Completed", "Completed", "Completed", "Completed"}},
        {"launcher.result.launch_failed", {"Falhou ao anexar", "Attach failed", "Attach failed", "Attach failed", "Attach failed", "Attach failed"}},
        {"launcher.result.offsets_failed", {"Validação de offsets falhou", "Offset validation failed", "Offset validation failed", "Offset validation failed", "Offset validation failed", "Offset validation failed"}},
        {"launcher.result.device_missing", {"Dispositivo em falta", "Device missing", "Device missing", "Device missing", "Device missing", "Device missing"}},
        {"launcher.result.game_not_found", {"Jogo não encontrado", "Game not found", "Game not found", "Juego no encontrado", "Jeu introuvable", "Gioco non trovato"}},
        {"launcher.result.process_ended", {"Jogo terminou", "Game ended", "Game ended", "Game ended", "Game ended", "Game ended"}},
        {"launcher.desc.ready", {"Componentes locais prontos para iniciar.", "Local components are ready to start.", "Local components are ready to start.", "Local components are ready to start.", "Local components are ready to start.", "Local components are ready to start."}},
        {"launcher.desc.not_installed", {"Faltam componentes locais necessários para este adaptador.", "Required local components for this adapter are missing.", "Required local components for this adapter are missing.", "Required local components for this adapter are missing.", "Required local components for this adapter are missing.", "Required local components for this adapter are missing."}},
        {"launcher.desc.needs_offsets", {"Os offsets existem, mas ainda não passaram a validação com o jogo em execução.", "Offsets exist but have not passed live validation yet.", "Offsets exist but have not passed live validation yet.", "Offsets exist but have not passed live validation yet.", "Offsets exist but have not passed live validation yet.", "Offsets exist but have not passed live validation yet."}},
        {"launcher.desc.device_missing", {"A última tentativa não encontrou comunicação válida com o dispositivo DMA/FPGA.", "The last attempt did not find valid communication with the DMA/FPGA device.", "The last attempt did not find valid communication with the DMA/FPGA device.", "The last attempt did not find valid communication with the DMA/FPGA device.", "The last attempt did not find valid communication with the DMA/FPGA device.", "The last attempt did not find valid communication with the DMA/FPGA device."}},
        {"launcher.desc.game_not_found", {"O DMA está ligado, mas o jogo não foi encontrado. Ele está aberto no PC principal?", "DMA is connected, but the game was not found. Is it open on the main PC?", "DMA is connected, but the game was not found. Is it open on the main PC?", "DMA está conectado, pero no se encontró el juego. ¿Está abierto en el PC principal?", "Le DMA est connecté, mais le jeu est introuvable. Est-il ouvert sur le PC principal ?", "DMA è connesso, ma il gioco non è stato trovato. È aperto sul PC principale?"}},
        {"launcher.desc.license_required", {"Inicia sessão normalmente e adiciona uma licença válida para desbloquear este jogo.", "Sign in normally and add a valid license to unlock this game.", "Sign in normally and add a valid license to unlock this game.", "Inicia sesión y añade una licencia válida para desbloquear este juego.", "Connecte-toi et ajoute une licence valide pour déverrouiller ce jeu.", "Accedi e aggiungi una licenza valida per sbloccare questo gioco."}},
        {"launcher.desc.update_required", {"Existe uma atualização obrigatória antes de iniciar novas sessões.", "A required update must be installed before starting new sessions.", "A required update must be installed before starting new sessions.", "A required update must be installed before starting new sessions.", "A required update must be installed before starting new sessions.", "A required update must be installed before starting new sessions."}},
        {"launcher.desc.coming_soon", {"O jogo já aparece na biblioteca, mas o backend ainda não está disponível.", "The game is already in the library, but its backend is not available yet.", "The game is already in the library, but its backend is not available yet.", "The game is already in the library, but its backend is not available yet.", "The game is already in the library, but its backend is not available yet.", "The game is already in the library, but its backend is not available yet."}},
        {"launcher.desc.launch_failed", {"A última tentativa de anexar ao jogo falhou. Consulta o diagnóstico e tenta novamente.", "The last attach attempt failed. Check Diagnostics and try again.", "The last attach attempt failed. Check Diagnostics and try again.", "The last attach attempt failed. Check Diagnostics and try again.", "The last attach attempt failed. Check Diagnostics and try again.", "The last attach attempt failed. Check Diagnostics and try again."}},
        {"launcher.desc.running", {"Foi detetado um processo suportado ou uma sessão ativa deste jogo.", "A supported process or active session for this game was detected.", "A supported process or active session for this game was detected.", "A supported process or active session for this game was detected.", "A supported process or active session for this game was detected.", "A supported process or active session for this game was detected."}},
        {"launcher.desc.beta", {"Backend disponível em estado Beta. Pode receber ajustes adicionais.", "Backend is available in Beta and may receive additional adjustments.", "Backend is available in Beta and may receive additional adjustments.", "Backend is available in Beta and may receive additional adjustments.", "Backend is available in Beta and may receive additional adjustments.", "Backend is available in Beta and may receive additional adjustments."}},
        {"launcher.toast.offsets_busy", {"Já existe uma atualização de offsets em curso.", "An offset refresh is already running.", "An offset refresh is already running.", "An offset refresh is already running.", "An offset refresh is already running.", "An offset refresh is already running."}},
        {"launcher.toast.offsets_unavailable", {"Atualização de offsets indisponível para este jogo.", "Offset refresh is unavailable for this game.", "Offset refresh is unavailable for this game.", "Offset refresh is unavailable for this game.", "Offset refresh is unavailable for this game.", "Offset refresh is unavailable for this game."}},
        {"launcher.toast.offsets_working", {"A atualizar offsets em segundo plano…", "Refreshing offsets in the background…", "Refreshing offsets in the background…", "Refreshing offsets in the background…", "Refreshing offsets in the background…", "Refreshing offsets in the background…"}},
        {"launcher.last_error", {"Último erro", "Last error", "Last error", "Last error", "Last error", "Last error"}},
        {"launcher.digital_rain", {"Chuva digital", "Digital rain", "Digital rain", "Digital rain", "Digital rain", "Digital rain"}},
        {"launcher.system_health", {"Estado do sistema", "System health", "System health", "System health", "System health", "System health"}},
        {"launcher.version", {"Versão do OmniGhost", "OmniGhost version", "OmniGhost version", "OmniGhost version", "OmniGhost version", "OmniGhost version"}},
        {"launcher.build", {"Compilação", "Build", "Build", "Build", "Build", "Build"}},
        {"launcher.windows", {"Windows", "Windows", "Windows", "Windows", "Windows", "Windows"}},
        {"launcher.renderer", {"Renderizador", "Renderer", "Renderer", "Renderer", "Renderer", "Renderer"}},
        {"launcher.renderer_ready", {"D3D11 pronto", "D3D11 ready", "D3D11 ready", "D3D11 ready", "D3D11 ready", "D3D11 ready"}},
        {"launcher.renderer_unavailable", {"D3D11 indisponível", "D3D11 unavailable", "D3D11 unavailable", "D3D11 unavailable", "D3D11 unavailable", "D3D11 unavailable"}},
        {"launcher.active_game", {"Jogo ativo", "Active game", "Active game", "Active game", "Active game", "Active game"}},
        {"launcher.no_game_selected", {"Nenhum jogo selecionado", "No game selected", "No game selected", "No game selected", "No game selected", "No game selected"}},
        {"launcher.updater", {"Atualizador", "Updater", "Updater", "Updater", "Updater", "Updater"}},
        {"launcher.updater_stage", {"Etapa do atualizador", "Updater stage", "Updater stage", "Updater stage", "Updater stage", "Updater stage"}},
        {"launcher.log_path", {"Localização do registo", "Log path", "Log path", "Log path", "Log path", "Log path"}},
        {"launcher.unavailable", {"Indisponível", "Unavailable", "Unavailable", "Unavailable", "Unavailable", "Unavailable"}},
        {"launcher.session", {"Sessão", "Session", "Session", "Session", "Session", "Session"}},
        {"launcher.copy_diagnostics", {"Copiar diagnóstico", "Copy diagnostics", "Copy diagnostics", "Copy diagnostics", "Copy diagnostics", "Copy diagnostics"}},
        {"launcher.diagnostics_copied", {"Diagnóstico copiado.", "Diagnostics copied.", "Diagnostics copied.", "Diagnostics copied.", "Diagnostics copied.", "Diagnostics copied."}},
        {"launcher.open_logs_folder", {"Abrir pasta dos registos", "Open logs folder", "Open logs folder", "Open logs folder", "Open logs folder", "Open logs folder"}},
        {"launcher.create_diagnostics_package", {"Criar pacote de diagnóstico", "Create diagnostics package", "Create diagnostics package", "Create diagnostics package", "Create diagnostics package", "Create diagnostics package"}},
        {"launcher.diagnostics_package_created", {"Pacote de diagnóstico criado.", "Diagnostics package created.", "Diagnostics package created.", "Diagnostics package created.", "Diagnostics package created.", "Diagnostics package created."}},
        {"launcher.diagnostics_package_failed", {"Falha ao criar o pacote de diagnóstico.", "Failed to create diagnostics package.", "Failed to create diagnostics package.", "Failed to create diagnostics package.", "Failed to create diagnostics package.", "Failed to create diagnostics package."}},
        {"launcher.build_metadata", {"Metadados da compilação", "Build metadata", "Build metadata", "Build metadata", "Build metadata", "Build metadata"}},
        {"launcher.build_id", {"ID da compilação", "Build ID", "Build ID", "Build ID", "Build ID", "Build ID"}},
        {"launcher.commit_source", {"Commit/origem", "Commit/source", "Commit/source", "Commit/source", "Commit/source", "Commit/source"}},
        {"launcher.source_provenance", {"Proveniência do código", "Source provenance", "Source provenance", "Source provenance", "Source provenance", "Source provenance"}},
        {"launcher.build_utc", {"Compilação UTC", "Build UTC", "Build UTC", "Build UTC", "Build UTC", "Build UTC"}},
        {"launcher.msvc_tools", {"Ferramentas MSVC", "MSVC tools", "MSVC tools", "MSVC tools", "MSVC tools", "MSVC tools"}},
        {"launcher.compiler", {"Compilador", "Compiler", "Compiler", "Compiler", "Compiler", "Compiler"}},
        {"launcher.release_channel", {"Canal de publicação", "Release channel", "Release channel", "Release channel", "Release channel", "Release channel"}},
        {"launcher.reproducible", {"Reproduzível", "Reproducible", "Reproducible", "Reproducible", "Reproducible", "Reproducible"}},
        {"launcher.yes", {"Sim", "Yes", "Yes", "Yes", "Yes", "Yes"}},
        {"launcher.no", {"Não", "No", "No", "No", "No", "No"}},
        {"launcher.installation", {"Instalação", "Installation", "Installation", "Installation", "Installation", "Installation"}},
        {"launcher.integrity", {"Integridade", "Integrity", "Integrity", "Integrity", "Integrity", "Integrity"}},
        {"launcher.integrity_verified", {"Verificada", "Verified", "Verified", "Verified", "Verified", "Verified"}},
        {"launcher.integrity_repair_needed", {"Reparação necessária", "Repair needed", "Repair needed", "Repair needed", "Repair needed", "Repair needed"}},
        {"launcher.integrity_checking", {"A verificar…", "Checking…", "Checking…", "Checking…", "Checking…", "Checking…"}},
        {"launcher.integrity_manifest_missing", {"Manifesto em falta", "Manifest missing", "Manifest missing", "Manifest missing", "Manifest missing", "Manifest missing"}},
        {"launcher.integrity_not_checked", {"Não verificada", "Not checked", "Not checked", "Not checked", "Not checked", "Not checked"}},
        {"launcher.verify_installation", {"Verificar instalação", "Verify installation", "Verify installation", "Verify installation", "Verify installation", "Verify installation"}},
        {"launcher.verifying", {"A verificar…", "Verifying…", "Verifying…", "Verifying…", "Verifying…", "Verifying…"}},
        {"launcher.repair_installation", {"Reparar instalação", "Repair installation", "Repair installation", "Repair installation", "Repair installation", "Repair installation"}},
        {"launcher.preparing_repair", {"A preparar reparação…", "Preparing repair…", "Preparing repair…", "Preparing repair…", "Preparing repair…", "Preparing repair…"}},
        {"launcher.settings.description", {"Preferências globais separadas dos perfis de cada jogo.", "Global preferences separated from each game's profiles.", "Global preferences separated from each game's profiles.", "Global preferences separated from each game's profiles.", "Global preferences separated from each game's profiles.", "Global preferences separated from each game's profiles."}},
        {"launcher.settings.general", {"Geral", "General", "General", "General", "General", "General"}},
        {"launcher.settings.appearance", {"Aspeto", "Appearance", "Appearance", "Appearance", "Appearance", "Appearance"}},
        {"launcher.settings.overlay", {"Sobreposição", "Overlay", "Overlay", "Overlay", "Overlay", "Overlay"}},
        {"launcher.settings.input", {"Controlos", "Input", "Input", "Input", "Input", "Input"}},
        {"launcher.settings.devices", {"Dispositivos", "Devices", "Devices", "Devices", "Devices", "Devices"}},
        {"launcher.settings.licenses", {"Licenças", "Licenses", "Licenses", "Licenses", "Licenses", "Licenses"}},
        {"launcher.settings.about", {"Sobre", "About", "About", "About", "About", "About"}},
        {"launcher.advanced", {"Avançado", "Advanced", "Advanced", "Advanced", "Advanced", "Advanced"}},
        {"launcher.advanced_help", {"Os controlos experimentais e de desenvolvimento ficam ocultos por predefinição.", "Experimental and developer controls are hidden by default.", "Experimental and developer controls are hidden by default.", "Experimental and developer controls are hidden by default.", "Experimental and developer controls are hidden by default.", "Experimental and developer controls are hidden by default."}},
        {"launcher.start_behavior", {"Página inicial", "Start behavior", "Start behavior", "Start behavior", "Start behavior", "Start behavior"}},
        {"launcher.last_game", {"Último jogo", "Last game", "Last game", "Last game", "Last game", "Last game"}},
        {"launcher.remember_last_game", {"Recordar o último jogo", "Remember last game", "Remember last game", "Remember last game", "Remember last game", "Remember last game"}},
        {"launcher.minimize_behavior", {"Ao minimizar", "Minimize behavior", "Minimize behavior", "Minimize behavior", "Minimize behavior", "Minimize behavior"}},
        {"launcher.minimize", {"Minimizar", "Minimize", "Minimize", "Minimize", "Minimize", "Minimize"}},
        {"launcher.keep_open", {"Manter aberto", "Keep open", "Keep open", "Keep open", "Keep open", "Keep open"}},
        {"launcher.close_behavior", {"Ao fechar", "Close behavior", "Close behavior", "Close behavior", "Close behavior", "Close behavior"}},
        {"launcher.exit_app", {"Sair do OmniGhost", "Exit OmniGhost", "Exit OmniGhost", "Exit OmniGhost", "Exit OmniGhost", "Exit OmniGhost"}},
        {"launcher.minimize_taskbar", {"Minimizar para a barra de tarefas", "Minimize to taskbar", "Minimize to taskbar", "Minimize to taskbar", "Minimize to taskbar", "Minimize to taskbar"}},
        {"launcher.auto_save_game_changes", {"Guardar automaticamente as alterações dos jogos", "Auto-save game changes", "Auto-save game changes", "Auto-save game changes", "Auto-save game changes", "Auto-save game changes"}},
        {"launcher.import_export", {"Importar / Exportar", "Import / Export", "Import / Export", "Import / Export", "Import / Export", "Import / Export"}},
        {"launcher.export_settings", {"Exportar definições", "Export settings", "Export settings", "Export settings", "Export settings", "Export settings"}},
        {"launcher.import_settings", {"Importar definições", "Import settings", "Import settings", "Import settings", "Import settings", "Import settings"}},
        {"launcher.settings_exported", {"Definições exportadas.", "Settings exported.", "Settings exported.", "Settings exported.", "Settings exported.", "Settings exported."}},
        {"launcher.settings_imported", {"Definições importadas.", "Settings imported.", "Settings imported.", "Settings imported.", "Settings imported.", "Settings imported."}},
        {"launcher.settings_save_failed", {"Falha ao guardar as definições.", "Failed to save settings.", "Failed to save settings.", "Failed to save settings.", "Failed to save settings.", "Failed to save settings."}},
        {"launcher.reset", {"Reposição", "Reset", "Reset", "Reset", "Reset", "Reset"}},
        {"launcher.reset_global_help", {"A reposição global altera apenas as definições gerais; os perfis de cada jogo não são apagados.", "Global reset only changes global settings; game profiles are not deleted.", "Global reset only changes global settings; game profiles are not deleted.", "Global reset only changes global settings; game profiles are not deleted.", "Global reset only changes global settings; game profiles are not deleted.", "Global reset only changes global settings; game profiles are not deleted."}},
        {"launcher.reset_global", {"Repor tudo", "Reset all", "Reset all", "Reset all", "Reset all", "Reset all"}},
        {"launcher.animation", {"Animações", "Animation", "Animation", "Animation", "Animation", "Animation"}},
        {"launcher.accent", {"Cor de destaque", "Accent", "Accent", "Accent", "Accent", "Accent"}},
        {"launcher.advanced_appearance", {"Avançado · Aspeto", "Advanced · Appearance", "Advanced · Appearance", "Advanced · Appearance", "Advanced · Appearance", "Advanced · Appearance"}},
        {"launcher.manual_performance", {"Modo de desempenho manual", "Manual performance mode", "Manual performance mode", "Manual performance mode", "Manual performance mode", "Manual performance mode"}},
        {"launcher.particles", {"Partículas", "Particles", "Particles", "Particles", "Particles", "Particles"}},
        {"launcher.snow_effect", {"Efeito de neve", "Snow effect", "Snow effect", "Snow effect", "Snow effect", "Snow effect"}},
        {"launcher.background_opacity", {"Opacidade do fundo", "Background opacity", "Background opacity", "Background opacity", "Background opacity", "Background opacity"}},
        {"launcher.show_fps", {"Mostrar FPS", "Show FPS", "Show FPS", "Show FPS", "Show FPS", "Show FPS"}},
        {"launcher.hotkey_overlay", {"Mostrar atalhos na sobreposição", "Hotkey overlay", "Hotkey overlay", "Hotkey overlay", "Hotkey overlay", "Hotkey overlay"}},
        {"launcher.monitor_auto", {"Automático / monitor atual", "Auto / current monitor", "Auto / current monitor", "Auto / current monitor", "Auto / current monitor", "Auto / current monitor"}},
        {"launcher.monitor", {"Monitor", "Monitor", "Monitor", "Monitor", "Monitor", "Monitor"}},
        {"launcher.primary", {"Principal", "Primary", "Primary", "Primary", "Primary", "Primary"}},
        {"launcher.menu", {"Menu", "Menu", "Menu", "Menu", "Menu", "Menu"}},
        {"launcher.aim", {"Mira", "Aim", "Aim", "Aim", "Aim", "Aim"}},
        {"launcher.vehicle", {"Veículo", "Vehicle", "Vehicle", "Vehicle", "Vehicle", "Vehicle"}},
        {"launcher.hotkey_help", {"A tecla Escape limpa o atalho durante a captura. O encaminhamento dos dispositivos é configurado na página Dispositivos.", "Escape clears the binding while capturing. Device routing is configured on the Devices page.", "Escape clears the binding while capturing. Device routing is configured on the Devices page.", "Escape clears the binding while capturing. Device routing is configured on the Devices page.", "Escape clears the binding while capturing. Device routing is configured on the Devices page.", "Escape clears the binding while capturing. Device routing is configured on the Devices page."}},
        {"launcher.online_licensing", {"Licenciamento online", "Online entitlements", "Online entitlements", "Online entitlements", "Online entitlements", "Online entitlements"}},
        {"launcher.keyauth_provider_help", {"As licenças adicionais e separadas por jogo serão aceites aqui quando o fornecedor KeyAuth estiver configurado.", "Additional per-game licenses will be accepted here when the KeyAuth provider is configured.", "Additional per-game licenses will be accepted here when the KeyAuth provider is configured.", "Additional per-game licenses will be accepted here when the KeyAuth provider is configured.", "Additional per-game licenses will be accepted here when the KeyAuth provider is configured.", "Additional per-game licenses will be accepted here when the KeyAuth provider is configured."}},
        {"launcher.stable", {"Estável", "Stable", "Stable", "Stable", "Stable", "Stable"}},
        {"launcher.development", {"Desenvolvimento", "Development", "Development", "Development", "Development", "Development"}},
        {"launcher.stable_publish_locked", {"Estável (fixo na compilação Publish)", "Stable (locked by Publish build)", "Stable (locked by Publish build)", "Stable (locked by Publish build)", "Stable (locked by Publish build)", "Stable (locked by Publish build)"}},
        {"launcher.development_tester_locked", {"Desenvolvimento (fixo na compilação Tester)", "Development (locked by Tester build)", "Development (locked by Tester build)", "Development (locked by Tester build)", "Development (locked by Tester build)", "Development (locked by Tester build)"}},
        {"launcher.auto_check", {"Procurar atualizações automaticamente", "Auto-check", "Auto-check", "Auto-check", "Auto-check", "Auto-check"}},
        {"launcher.auto_download", {"Transferir atualizações automaticamente", "Auto-download", "Auto-download", "Auto-download", "Auto-download", "Auto-download"}},
        {"launcher.install_on_exit", {"Instalar ao sair", "Install on exit", "Install on exit", "Install on exit", "Install on exit", "Install on exit"}},
        {"launcher.check_now", {"Procurar agora", "Check now", "Check now", "Check now", "Check now", "Check now"}},
        {"launcher.update_channel_help", {"O canal selecionado define as versões aceites pelo atualizador. A integridade do pacote continua a ser validada pelo tamanho e pelo SHA-256.", "The selected channel defines which versions the updater accepts. Package integrity is still validated by size and SHA-256.", "The selected channel defines which versions the updater accepts. Package integrity is still validated by size and SHA-256.", "The selected channel defines which versions the updater accepts. Package integrity is still validated by size and SHA-256.", "The selected channel defines which versions the updater accepts. Package integrity is still validated by size and SHA-256.", "The selected channel defines which versions the updater accepts. Package integrity is still validated by size and SHA-256."}},
        {"launcher.language_help", {"A alteração é aplicada imediatamente aos textos localizados.", "The change is immediately applied to localized text.", "The change is immediately applied to localized text.", "The change is immediately applied to localized text.", "The change is immediately applied to localized text.", "The change is immediately applied to localized text."}},
        {"launcher.diagnostics_help", {"A página de Diagnóstico reúne informações da compilação, Windows, renderizador, DMA, entrada, jogo, offsets, atualizador e registos.", "The Diagnostics page contains build, Windows, renderer, DMA, input, game, offsets, updater and log information.", "The Diagnostics page contains build, Windows, renderer, DMA, input, game, offsets, updater and log information.", "The Diagnostics page contains build, Windows, renderer, DMA, input, game, offsets, updater and log information.", "The Diagnostics page contains build, Windows, renderer, DMA, input, game, offsets, updater and log information.", "The Diagnostics page contains build, Windows, renderer, DMA, input, game, offsets, updater and log information."}},
        {"launcher.open_diagnostics", {"Abrir diagnóstico", "Open Diagnostics", "Open Diagnostics", "Open Diagnostics", "Open Diagnostics", "Open Diagnostics"}},
        {"launcher.channel", {"Canal", "Channel", "Channel", "Channel", "Channel", "Channel"}},
        {"launcher.architecture", {"Arquitetura", "Architecture", "Architecture", "Architecture", "Architecture", "Architecture"}},
        {"launcher.about_metadata_help", {"Os metadados da compilação são incluídos no Diagnóstico e na proveniência da versão publicada.", "Build metadata is captured into Diagnostics and release provenance.", "Build metadata is captured into Diagnostics and release provenance.", "Build metadata is captured into Diagnostics and release provenance.", "Build metadata is captured into Diagnostics and release provenance.", "Build metadata is captured into Diagnostics and release provenance."}},
        {"launcher.reset_this_page", {"Repor esta página", "Reset this page", "Reset this page", "Reset this page", "Reset this page", "Reset this page"}},
        {"launcher.page_reset", {"Página reposta.", "Page reset.", "Page reset.", "Page reset.", "Page reset.", "Page reset."}},
        {"launcher.global_reset_title", {"Repor definições globais", "Reset global settings", "Reset global settings", "Reset global settings", "Reset global settings", "Reset global settings"}},
        {"launcher.global_reset_message", {"Isto repõe todas as definições globais. Os perfis de cada jogo e as credenciais não são apagados.", "This resets all global settings. Game profiles and credentials are not deleted.", "This resets all global settings. Game profiles and credentials are not deleted.", "This resets all global settings. Game profiles and credentials are not deleted.", "This resets all global settings. Game profiles and credentials are not deleted.", "This resets all global settings. Game profiles and credentials are not deleted."}},
        {"launcher.global_settings_reset", {"Definições globais repostas.", "Global settings reset.", "Global settings reset.", "Global settings reset.", "Global settings reset.", "Global settings reset."}},
        {"launcher.minimize_disabled", {"A opção de minimizar está desativada em Definições > Geral.", "Minimize is disabled in Settings > General.", "Minimize is disabled in Settings > General.", "Minimize is disabled in Settings > General.", "Minimize is disabled in Settings > General.", "Minimize is disabled in Settings > General."}},
        {"launcher.game_settings_reset_message", {"Esta ação repõe apenas a configuração de %s. As definições globais não são alteradas.", "This only resets %s configuration. Global settings are not changed.", "This only resets %s configuration. Global settings are not changed.", "This only resets %s configuration. Global settings are not changed.", "This only resets %s configuration. Global settings are not changed.", "This only resets %s configuration. Global settings are not changed."}},
        {"launcher.game.fivem.description", {"GTA V Roleplay · DMA Premium", "GTA V Roleplay · Premium DMA", "GTA V Roleplay · Premium DMA", "GTA V Roleplay · Premium DMA", "GTA V Roleplay · Premium DMA", "GTA V Roleplay · Premium DMA"}},
        {"launcher.game.fivem.tagline", {"INTERPRETAÇÃO", "ROLEPLAY", "ROLEPLAY", "ROLEPLAY", "ROLEPLAY", "ROLEPLAY"}},
        {"launcher.game.cs2.description", {"Counter-Strike 2 · DMA Premium", "Counter-Strike 2 · Premium DMA", "Counter-Strike 2 · Premium DMA", "Counter-Strike 2 · Premium DMA", "Counter-Strike 2 · Premium DMA", "Counter-Strike 2 · Premium DMA"}},
        {"launcher.game.cs2.tagline", {"COMPETITIVO", "COMPETITIVE", "COMPETITIVE", "COMPETITIVE", "COMPETITIVE", "COMPETITIVE"}},
        {"launcher.game.rust.description", {"ESP, mira e opções diversas via DMA — mesmo menu OmniGhost.", "ESP, aim and miscellaneous features via DMA — same OmniGhost menu.", "ESP, aim and miscellaneous features via DMA — same OmniGhost menu.", "ESP, aim and miscellaneous features via DMA — same OmniGhost menu.", "ESP, aim and miscellaneous features via DMA — same OmniGhost menu.", "ESP, aim and miscellaneous features via DMA — same OmniGhost menu."}},
        {"launcher.game.rust.tagline", {"SOBREVIVÊNCIA DMA", "SURVIVAL DMA", "SURVIVAL DMA", "SURVIVAL DMA", "SURVIVAL DMA", "SURVIVAL DMA"}},
        {"launcher.game.warzone.description", {"Warzone · componente DMA integrado", "Warzone · integrated DMA runtime", "Warzone · integrated DMA runtime", "Warzone · integrated DMA runtime", "Warzone · integrated DMA runtime", "Warzone · integrated DMA runtime"}},
        {"launcher.game.warzone.tagline", {"BATALHA REAL", "BATTLE ROYALE", "BATTLE ROYALE", "BATTLE ROYALE", "BATTLE ROYALE", "BATTLE ROYALE"}},
        {"launcher.game.valorant.description", {"Valorant · componente DMA e menu dedicado", "Valorant · DMA runtime and dedicated menu", "Valorant · DMA runtime and dedicated menu", "Valorant · DMA runtime and dedicated menu", "Valorant · DMA runtime and dedicated menu", "Valorant · DMA runtime and dedicated menu"}},
        {"launcher.game.valorant.tagline", {"TÁTICO", "TACTICAL", "TACTICAL", "TACTICAL", "TACTICAL", "TACTICAL"}},
        {"launcher.game.apex.description", {"Planeado · Em breve · cartão apenas na biblioteca", "Roadmap · Coming soon · library card only", "Roadmap · Coming soon · library card only", "Roadmap · Coming soon · library card only", "Roadmap · Coming soon · library card only", "Roadmap · Coming soon · library card only"}},
        {"launcher.game.apex.tagline", {"EM BREVE", "COMING SOON", "COMING SOON", "COMING SOON", "COMING SOON", "COMING SOON"}},
        {"launcher.game.fortnite.description", {"Planeado · Em breve · cartão apenas na biblioteca", "Roadmap · Coming soon · library card only", "Roadmap · Coming soon · library card only", "Roadmap · Coming soon · library card only", "Roadmap · Coming soon · library card only", "Roadmap · Coming soon · library card only"}},
        {"launcher.game.fortnite.tagline", {"EM BREVE", "COMING SOON", "COMING SOON", "COMING SOON", "COMING SOON", "COMING SOON"}},
        {"header.control", {"CENTRO OPERACIONAL", "OPERATIONS CENTER", "OPERATIONS CENTER", "OPERATIONS CENTER", "OPERATIONS CENTER", "OPERATIONS CENTER"}},
        {"header.premium", {"PREMIUM DMA", "PREMIUM DMA", "PREMIUM DMA", "PREMIUM DMA", "PREMIUM DMA", "PREMIUM DMA"}},
        {"footer.connected", {"Ligado", "Connected", "Verbunden", "Conectado", "Connecte", "Connesso"}},
        {"footer.offline", {"Sem ligação", "Offline", "Offline", "Desconectado", "Hors ligne", "Offline"}},
        {"footer.build", {"Versao %s", "Build %s", "Build %s", "Build %s", "Build %s", "Build %s"}},
        {"footer.discord", {"Discord", "Discord", "Discord", "Discord", "Discord", "Discord"}},
        {"footer.fps", {"%.0f FPS", "%.0f FPS", "%.0f FPS", "%.0f FPS", "%.0f FPS", "%.0f FPS"}},
        {"footer.ping", {"%d ms", "%d ms", "%d ms", "%d ms", "%d ms", "%d ms"}},
        {"footer.players", {"%d jogadores", "%d players", "%d players", "%d players", "%d players", "%d players"}},
        {"common.active", {"Ativo", "Active", "Aktiv", "Activo", "Actif", "Attivo"}},
        {"common.off", {"Desligado", "Off", "Aus", "Off", "Off", "Off"}},
        {"common.show", {"Mostrar", "Show", "Anzeigen", "Mostrar", "Afficher", "Mostra"}},
        {"common.hide", {"Ocultar", "Hide", "Ausblenden", "Ocultar", "Masquer", "Nascondi"}},
        {"common.top", {"Topo", "Top", "Top", "Top", "Top", "Top"}},
        {"common.center", {"Centro", "Center", "Center", "Center", "Center", "Center"}},
        {"common.bottom", {"Baixo", "Bottom", "Bottom", "Bottom", "Bottom", "Bottom"}},
        {"common.connect", {"Conectar", "Connect", "Verbinden", "Conectar", "Connecter", "Connetti"}},
        {"common.test", {"Testar", "Test", "Testen", "Probar", "Tester", "Test"}},
        {"common.exit", {"SAIR", "EXIT", "BEENDEN", "SALIR", "QUITTER", "ESCI"}},
        {"common.search", {"Procurar", "Search", "Suchen", "Buscar", "Rechercher", "Cerca"}},
        {"common.name", {"Nome", "Name", "Name", "Nombre", "Nom", "Nome"}},
        {"common.id", {"ID", "ID", "ID", "ID", "ID", "ID"}},
        {"common.distance", {"Distância", "Distance", "Distanz", "Distancia", "Distance", "Distanza"}},
        {"common.dist_short", {"Dist.", "Dist.", "Dist.", "Dist.", "Dist.", "Dist."}},
        {"common.load", {"Carregar", "Load", "Laden", "Cargar", "Charger", "Carica"}},
        {"common.delete", {"Eliminar", "Delete", "Loschen", "Eliminar", "Supprimer", "Elimina"}},
        {"common.refresh", {"Atualizar", "Refresh", "Aktualisieren", "Actualizar", "Actualiser", "Aggiorna"}},
        {"common.enable", {"Ativar", "Enable", "Enable", "Enable", "Enable", "Enable"}},
        {"common.enabled", {"Ativado", "Enabled", "Enabled", "Enabled", "Enabled", "Enabled"}},
        {"status.ok", {"OK", "OK", "OK", "OK", "OK", "OK"}},
        {"status.offline", {"Sem ligação", "Offline", "Offline", "Desconectado", "Hors ligne", "Offline"}},
        {"status.ping_ok", {"Ping OK", "Ping OK", "Ping OK", "Ping OK", "Ping OK", "Ping OK"}},
        {"status.device_ok", {"Dispositivo OK", "Device OK", "Device OK", "Device OK", "Device OK", "Device OK"}},
        {"status.copied", {"Copiado para a area de transferencia", "Copied to clipboard", "Copied to clipboard", "Copied to clipboard", "Copied to clipboard", "Copied to clipboard"}},
        {"status.pasted", {"Colado da area de transferencia", "Pasted from clipboard", "Pasted from clipboard", "Pasted from clipboard", "Pasted from clipboard", "Pasted from clipboard"}},
        {"status.reset", {"Reposto para o padrão", "Reset to defaults", "Reset to defaults", "Reset to defaults", "Reset to defaults", "Reset to defaults"}},
        {"status.config_loaded", {"Configuracao carregada", "Configuration loaded", "Configuration loaded", "Configuration loaded", "Configuration loaded", "Configuration loaded"}},
        {"status.config_saved", {"Configuracao guardada", "Configuration saved", "Configuration saved", "Configuration saved", "Configuration saved", "Configuration saved"}},
        {"status.friend_added", {"Amigo adicionado", "Friend added", "Friend added", "Friend added", "Friend added", "Friend added"}},
        {"status.friend_removed", {"Amigo removido", "Friend removed", "Friend removed", "Friend removed", "Friend removed", "Friend removed"}},
        {"status.hotkey_set", {"Tecla definida", "Hotkey set", "Hotkey set", "Hotkey set", "Hotkey set", "Hotkey set"}},
        {"status.unlock_req", {"Destrancar solicitado", "Unlock requested", "Unlock requested", "Unlock requested", "Unlock requested", "Unlock requested"}},
        {"status.press_key", {"Carrega uma tecla...", "Press a key...", "Press a key...", "Press a key...", "Press a key...", "Press a key..."}},
        {"cfg.auto_perf", {"Desempenho automático (FPS < 40)", "Auto Performance (FPS < 40)", "Auto Performance (FPS < 40)", "Auto Performance (FPS < 40)", "Auto Performance (FPS < 40)", "Auto Performance (FPS < 40)"}},
        {"cfg.auto_perf_hint", {"Quando o FPS cai abaixo de 40, ativa Performance automaticamente.", "When FPS drops below 40, Performance turns on automatically.", "When FPS drops below 40, Performance turns on automatically.", "When FPS drops below 40, Performance turns on automatically.", "When FPS drops below 40, Performance turns on automatically.", "When FPS drops below 40, Performance turns on automatically."}},
        {"cfg.hotkey_overlay", {"Hotkey Overlay", "Hotkey Overlay", "Hotkey Overlay", "Hotkey Overlay", "Hotkey Overlay", "Hotkey Overlay"}},
        {"aim.threat", {"Prioridade de Ameaca", "Threat Priority", "Threat Priority", "Threat Priority", "Threat Priority", "Threat Priority"}},
        {"aim.prediction", {"Predicao por Velocidade", "Velocity Prediction", "Velocity Prediction", "Velocity Prediction", "Velocity Prediction", "Velocity Prediction"}},
        {"aim.trigger_head", {"Disparar apenas na cabeça", "Trigger Head Only", "Trigger Head Only", "Trigger Head Only", "Trigger Head Only", "Trigger Head Only"}},
        {"vis.search", {"Procurar funcionalidades ESP...", "Search ESP features...", "Search ESP features...", "Search ESP features...", "Search ESP features...", "Search ESP features..."}},
        {"vis.configs", {"DEFINIÇÕES DO ESP", "ESP CONFIGS", "ESP CONFIGS", "ESP CONFIGS", "ESP CONFIGS", "ESP CONFIGS"}},
        {"vis.customize", {"PERSONALIZACAO", "CUSTOMIZE", "CUSTOMIZE", "CUSTOMIZE", "CUSTOMIZE", "CUSTOMIZE"}},
        {"vis.preview", {"PRÉ-VISUALIZAÇÃO DO ESP", "ESP PREVIEW", "ESP PREVIEW", "ESP PREVIEW", "ESP PREVIEW", "ESP PREVIEW"}},
        {"vis.enabled", {"ESP Ativado", "ESP Enabled", "ESP Enabled", "ESP Enabled", "ESP Enabled", "ESP Enabled"}},
        {"vis.self", {"ESP Proprio", "Self ESP", "Self ESP", "Self ESP", "Self ESP", "Self ESP"}},
        {"vis.npc", {"NPCs ESP", "NPC ESP", "NPC ESP", "NPC ESP", "NPC ESP", "NPC ESP"}},
        {"vis.show_dead", {"Mostrar Mortos", "Show Dead", "Show Dead", "Show Dead", "Show Dead", "Show Dead"}},
        {"vis.visible_check", {"Verificação de visibilidade", "Visible Check", "Visible Check", "Visible Check", "Visible Check", "Visible Check"}},
        {"vis.esp_configs", {"Definições do ESP", "ESP Configs", "ESP Configs", "ESP Configs", "ESP Configs", "ESP Configs"}},
        {"vis.enable", {"Ativar ESP", "Enable ESP", "Enable ESP", "Enable ESP", "Enable ESP", "Enable ESP"}},
        {"vis.self_esp", {"ESP do próprio jogador", "Self ESP", "Self ESP", "Self ESP", "Self ESP", "Self ESP"}},
        {"vis.team_check", {"Verificação de equipa", "Team Check", "Team Check", "Team Check", "Team Check", "Team Check"}},
        {"vis.skeleton", {"Esqueleto", "Skeleton", "Skeleton", "Skeleton", "Skeleton", "Skeleton"}},
        {"vis.joints", {"Articulações", "Joints", "Joints", "Joints", "Joints", "Joints"}},
        {"aim.smooth", {"Suavidade", "Smooth", "Smooth", "Smooth", "Smooth", "Smooth"}},
        {"device.reinit_dma", {"Reiniciar DMA", "Reinitialize DMA", "DMA neu initialisieren", "Reiniciar DMA", "Réinitialiser le DMA", "Reinizializza DMA"}},
        {"rust.world.hackable_crate", {"Caixa hackeável", "Hackable crate", "Hackbare Kiste", "Caja pirateable", "Caisse piratable", "Cassa hackerabile"}},
        {"vis.head_circle", {"Círculo na cabeça", "Head Circle", "Head Circle", "Head Circle", "Head Circle", "Head Circle"}},
        {"vis.health_bar", {"Barra de vida", "Health Bar", "Health Bar", "Health Bar", "Health Bar", "Health Bar"}},
        {"vis.armor_bar", {"Barra de armadura", "Armor Bar", "Armor Bar", "Armor Bar", "Armor Bar", "Armor Bar"}},
        {"vis.weapon", {"Nome da arma", "Weapon Name", "Weapon Name", "Weapon Name", "Weapon Name", "Weapon Name"}},
        {"vis.box_2d", {"Caixa 2D", "2D Box", "2D Box", "2D Box", "2D Box", "2D Box"}},
        {"vis.corner", {"Caixa de canto", "Corner Box", "Corner Box", "Corner Box", "Corner Box", "Corner Box"}},
        {"vis.snaplines", {"Linhas guia", "Snaplines", "Snaplines", "Snaplines", "Snaplines", "Snaplines"}},
        {"vis.distance", {"Distância", "Distance", "Distance", "Distance", "Distance", "Distance"}},
        {"vis.name", {"Nome do jogador", "Player Name", "Player Name", "Player Name", "Player Name", "Player Name"}},
        {"vis.max_dist", {"Distância máxima", "Max Distance", "Max Distance", "Max Distance", "Max Distance", "Max Distance"}},
        {"vis.colors", {"Cores", "Colors", "Colors", "Colors", "Colors", "Colors"}},
        {"vis.col_enemy", {"Inimigo", "Enemy", "Enemy", "Enemy", "Enemy", "Enemy"}},
        {"vis.col_team", {"Team", "Team", "Team", "Team", "Team", "Team"}},
        {"vis.col_skeleton", {"Esqueleto", "Skeleton", "Skeleton", "Skeleton", "Skeleton", "Skeleton"}},
        {"vis.col_name", {"Nome", "Name", "Name", "Name", "Name", "Name"}},
        {"vis.extras", {"Extras", "Extras", "Extras", "Extras", "Extras", "Extras"}},
        {"vis.weapon_icons", {"Ícone da arma", "Weapon Icons", "Weapon Icons", "Weapon Icons", "Weapon Icons", "Weapon Icons"}},
        {"vis.show_bots", {"Mostrar bots", "Show Bots", "Show Bots", "Show Bots", "Show Bots", "Show Bots"}},
        {"vis.bomb", {"Bomb timer", "Bomb Timer", "Bomb Timer", "Bomb Timer", "Bomb Timer", "Bomb Timer"}},
        {"vis.spectators", {"Spectator list", "Spectator List", "Spectator List", "Spectator List", "Spectator List", "Spectator List"}},
        {"vis.webradar", {"Radar Web", "Web Radar", "Web Radar", "Web Radar", "Web Radar", "Web Radar"}},

        {"vis.only_visible", {"Mostrar apenas visíveis", "Only Visible", "Only Visible", "Only Visible", "Only Visible", "Only Visible"}},
        {"vis.hide_text_vis", {"Ocultar textos nos visíveis", "Hide Text When Visible", "Hide Text When Visible", "Hide Text When Visible", "Hide Text When Visible", "Hide Text When Visible"}},
        {"vis.team_check", {"Verificação de equipa", "Team Check", "Team Check", "Team Check", "Team Check", "Team Check"}},
        {"vis.joints", {"Articulações", "Joints", "Joints", "Joints", "Joints", "Joints"}},
        {"aim.profiles", {"Perfis", "Profiles", "Profiles", "Profiles", "Profiles", "Profiles"}},
        {"aim.profile_legit", {"Minimal", "Minimal", "Minimal", "Minimal", "Minimal", "Minimal"}},
        {"aim.profile_rage", {"Visual", "Visual", "Visual", "Visual", "Visual", "Visual"}},
        {"aim.profile_legit_ok", {"Perfil Minimal aplicado", "Minimal profile applied", "Minimal profile applied", "Minimal profile applied", "Minimal profile applied", "Minimal profile applied"}},
        {"aim.profile_rage_ok", {"Perfil Visual aplicado", "Visual profile applied", "Visual profile applied", "Visual profile applied", "Visual profile applied", "Visual profile applied"}},
        {"aim.lock_beep", {"Beep no lock", "Lock beep", "Lock beep", "Lock beep", "Lock beep", "Lock beep"}},
        {"aim.crosshair", {"Crosshair custom", "Custom crosshair", "Custom crosshair", "Custom crosshair", "Custom crosshair", "Custom crosshair"}},
        {"aim.recoil_vis", {"Padrao recoil visual", "Recoil pattern visual", "Recoil pattern visual", "Recoil pattern visual", "Recoil pattern visual", "Recoil pattern visual"}},
        {"aim.crosshair_size", {"Tamanho crosshair", "Crosshair size", "Crosshair size", "Crosshair size", "Crosshair size", "Crosshair size"}},
        {"aim.crosshair_color", {"Cor crosshair", "Crosshair color", "Crosshair color", "Crosshair color", "Crosshair color", "Crosshair color"}},
        {"aim.trigger_show_fov", {"Mostrar FOV do disparo automático", "Show trigger FOV", "Show trigger FOV", "Show trigger FOV", "Show trigger FOV", "Show trigger FOV"}},
        {"aim.trigger_delay", {"Atraso do disparo automático", "Trigger delay", "Trigger delay", "Trigger delay", "Trigger delay", "Trigger delay"}},
        {"aim.trigger_random", {"Atraso adicional", "Extra delay", "Extra delay", "Extra delay", "Extra delay", "Extra delay"}},
        {"vis.radar", {"Radar jogadores", "Player radar", "Player radar", "Player radar", "Player radar", "Player radar"}},
        {"vis.radar_range", {"Alcance radar", "Radar range", "Radar range", "Radar range", "Radar range", "Radar range"}},
        {"vis.radar_size", {"Tamanho radar", "Radar size", "Radar size", "Radar size", "Radar size", "Radar size"}},
        {"vis.skeleton_lod", {"LOD do esqueleto", "Skeleton LOD", "Skeleton LOD", "Skeleton LOD", "Skeleton LOD", "Skeleton LOD"}},
        {"veh.speed", {"Velocidade", "Speed", "Speed", "Speed", "Speed", "Speed"}},
        {"cfg.auto_save", {"Guardar definições automaticamente", "Auto-save configs", "Auto-save configs", "Auto-save configs", "Auto-save configs", "Auto-save configs"}},
        {"vis.skeleton", {"Esqueleto", "Skeleton", "Skeleton", "Skeleton", "Skeleton", "Skeleton"}},
        {"vis.head_circle", {"Círculo na cabeça", "Head Circle", "Head Circle", "Head Circle", "Head Circle", "Head Circle"}},
        {"vis.health_bar", {"Barra de Vida", "Health Bar", "Health Bar", "Health Bar", "Health Bar", "Health Bar"}},
        {"vis.armor_bar", {"Barra de Armadura", "Armor Bar", "Armor Bar", "Armor Bar", "Armor Bar", "Armor Bar"}},
        {"vis.weapon_name", {"Nome da Arma", "Weapon Name", "Weapon Name", "Weapon Name", "Weapon Name", "Weapon Name"}},
        {"vis.box_2d", {"Caixa 2D", "2D Box", "2D Box", "2D Box", "2D Box", "2D Box"}},
        {"vis.corner_box", {"Caixa de Canto", "Corner Box", "Corner Box", "Corner Box", "Corner Box", "Corner Box"}},
        {"vis.filled_box", {"Caixa Preenchida", "Filled Box", "Filled Box", "Filled Box", "Filled Box", "Filled Box"}},
        {"vis.snaplines", {"Linhas Guia", "Snaplines", "Snaplines", "Snaplines", "Snaplines", "Snaplines"}},
        {"vis.distance", {"Distância", "Distance", "Distanz", "Distancia", "Distance", "Distanza"}},
        {"vis.player_name", {"Nome do Jogador", "Player Name", "Player Name", "Player Name", "Player Name", "Player Name"}},
        {"vis.player_id", {"ID do Jogador", "Player ID", "Player ID", "Player ID", "Player ID", "Player ID"}},
        {"vis.color_visible", {"Visibilidade", "Visibility", "Visibility", "Visibility", "Visibility", "Visibility"}},
        {"vis.color_dead", {"Mortos", "Dead", "Dead", "Dead", "Dead", "Dead"}},
        {"vis.color_knocked", {"Abatidos", "Knocked", "Knocked", "Knocked", "Knocked", "Knocked"}},
        {"vis.color_team", {"Cor da equipa", "Team Check", "Team Check", "Team Check", "Team Check", "Team Check"}},
        {"vis.color_skeleton", {"Esqueleto", "Skeleton", "Skeleton", "Skeleton", "Skeleton", "Skeleton"}},
        {"vis.color_points", {"Pontos do esqueleto", "Skeleton Points", "Skeleton Points", "Skeleton Points", "Skeleton Points", "Skeleton Points"}},
        {"vis.color_head", {"Círculo na cabeça", "Head Circle", "Head Circle", "Head Circle", "Head Circle", "Head Circle"}},
        {"vis.color_weapon", {"Nome Arma", "Weapon Name", "Weapon Name", "Weapon Name", "Weapon Name", "Weapon Name"}},
        {"vis.color_box2d", {"Caixa 2D", "2D Box", "2D Box", "2D Box", "2D Box", "2D Box"}},
        {"vis.color_corner", {"Caixa de Canto", "Corner Box", "Corner Box", "Corner Box", "Corner Box", "Corner Box"}},
        {"vis.color_snap", {"Linhas Guia", "Snaplines", "Snaplines", "Snaplines", "Snaplines", "Snaplines"}},
        {"vis.color_name", {"Nome Jogador", "Player Name", "Player Name", "Player Name", "Player Name", "Player Name"}},
        {"vis.color_id", {"ID Jogador", "Player ID", "Player ID", "Player ID", "Player ID", "Player ID"}},
        {"vis.color_dist", {"Distância", "Distance", "Distanz", "Distancia", "Distance", "Distanza"}},
        {"vis.color_npc", {"ESP NPCs", "NPC ESP", "NPC ESP", "NPC ESP", "NPC ESP", "NPC ESP"}},
        {"vis.rgb", {"Modo RGB (Arco-Iris)", "RGB Mode (Rainbow)", "RGB Mode (Rainbow)", "RGB Mode (Rainbow)", "RGB Mode (Rainbow)", "RGB Mode (Rainbow)"}},
        {"vis.snap_pos", {"Posicao Linhas Guia", "Snapline Position", "Snapline Position", "Snapline Position", "Snapline Position", "Snapline Position"}},
        {"vis.circle_type", {"Tipo de Circulo", "Circle Type", "Circle Type", "Circle Type", "Circle Type", "Circle Type"}},
        {"vis.circle_normal", {"Normal", "Normal", "Normal", "Normal", "Normal", "Normal"}},
        {"vis.circle_filled", {"Preenchido", "Filled", "Filled", "Filled", "Filled", "Filled"}},
        {"vis.circle_cross", {"Cruz", "Cross", "Cross", "Cross", "Cross", "Cross"}},
        {"aim.search", {"Procurar funcionalidades de mira...", "Search aim features...", "Search aim features...", "Search aim features...", "Search aim features...", "Search aim features..."}},
        {"aim.general", {"DEFINIÇÕES GERAIS", "GENERAL CONFIGS", "GENERAL CONFIGS", "GENERAL CONFIGS", "GENERAL CONFIGS", "GENERAL CONFIGS"}},
        {"aim.hitbox", {"Ponto de Impacto", "Hitbox", "Hitbox", "Hitbox", "Hitbox", "Hitbox"}},
        {"aim.fov_style", {"Estilo do FOV", "FOV Style", "FOV Style", "FOV Style", "FOV Style", "FOV Style"}},
        {"aim.visible_check", {"Verificar Visibilidade", "Visible Check", "Visible Check", "Visible Check", "Visible Check", "Visible Check"}},
        {"aim.closest", {"Alvo mais próximo da mira", "Closest to Crosshair", "Closest to Crosshair", "Closest to Crosshair", "Closest to Crosshair", "Closest to Crosshair"}},
        {"aim.aimbot", {"AIMBOT", "AIMBOT", "AIMBOT", "AIMBOT", "AIMBOT", "AIMBOT"}},
        {"aim.enable", {"Ativar", "Enable", "Enable", "Enable", "Enable", "Enable"}},
        {"aim.show_fov", {"Exibir FOV", "Show FOV", "Show FOV", "Show FOV", "Show FOV", "Show FOV"}},
        {"aim.fov_rgb", {"FOV RGB", "FOV RGB", "FOV RGB", "FOV RGB", "FOV RGB", "FOV RGB"}},
        {"aim.fov_color", {"Cor do FOV", "FOV Color", "FOV Color", "FOV Color", "FOV Color", "FOV Color"}},
        {"aim.fov_size", {"Tamanho do FOV", "FOV Size", "FOV Size", "FOV Size", "FOV Size", "FOV Size"}},
        {"aim.distance", {"Distância", "Distance", "Distanz", "Distancia", "Distance", "Distanza"}},
        {"aim.smooth_x", {"Suavidade X", "Smooth X", "Smooth X", "Smooth X", "Smooth X", "Smooth X"}},
        {"aim.smooth_y", {"Suavidade Y", "Smooth Y", "Smooth Y", "Smooth Y", "Smooth Y", "Smooth Y"}},
        {"aim.reaction", {"Tempo de Reacao", "Reaction Time", "Reaction Time", "Reaction Time", "Reaction Time", "Reaction Time"}},
        {"aim.humanize_title", {"Humanizacao", "Humanization", "Humanization", "Humanization", "Humanization", "Humanization"}},
        {"aim.humanize", {"Humanizar Mira", "Humanize Aim", "Humanize Aim", "Humanize Aim", "Humanize Aim", "Humanize Aim"}},
        {"aim.jitter", {"Oscilação", "Jitter", "Jitter", "Jitter", "Jitter", "Jitter"}},
        {"aim.accel", {"Aceleracao", "Acceleration", "Acceleration", "Acceleration", "Acceleration", "Acceleration"}},
        {"aim.overshoot", {"Probabilidade de ultrapassagem", "Overshoot Chance", "Overshoot Chance", "Overshoot Chance", "Overshoot Chance", "Overshoot Chance"}},
        {"aim.silent", {"MIRA SILENCIOSA", "SILENT AIM", "SILENT AIM", "SILENT AIM", "SILENT AIM", "SILENT AIM"}},
        {"aim.silent_enable", {"Ativar mira silenciosa", "Enable Silent", "Enable Silent", "Enable Silent", "Enable Silent", "Enable Silent"}},
        {"aim.silent_fov", {"Exibir FOV da mira silenciosa", "Show Silent FOV", "Show Silent FOV", "Show Silent FOV", "Show Silent FOV", "Show Silent FOV"}},
        {"aim.silent_rgb", {"FOV RGB da mira silenciosa", "Silent FOV RGB", "Silent FOV RGB", "Silent FOV RGB", "Silent FOV RGB", "Silent FOV RGB"}},
        {"aim.silent_color", {"Cor do FOV da mira silenciosa", "Silent FOV Color", "Silent FOV Color", "Silent FOV Color", "Silent FOV Color", "Silent FOV Color"}},
        {"aim.silent_size", {"Tamanho do FOV da mira silenciosa", "Silent FOV Size", "Silent FOV Size", "Silent FOV Size", "Silent FOV Size", "Silent FOV Size"}},
        {"aim.silent_dist", {"Distância da mira silenciosa", "Silent Distance", "Silent Distance", "Silent Distance", "Silent Distance", "Silent Distance"}},
        {"aim.hit_chance", {"Chance de Acerto", "Hit Chance", "Hit Chance", "Hit Chance", "Hit Chance", "Hit Chance"}},
        {"aim.miss_chance", {"Chance de Erro", "Miss Chance", "Miss Chance", "Miss Chance", "Miss Chance", "Miss Chance"}},
        {"aim.bone", {"Selecao de Osso", "Bone Selector", "Bone Selector", "Bone Selector", "Bone Selector", "Bone Selector"}},
        {"aim.legit", {"Ajuste Minimal", "Minimal tuning", "Minimal tuning", "Minimal tuning", "Minimal tuning", "Minimal tuning"}},
        {"aim.rage", {"Ajuste Visual", "Visual tuning", "Visual tuning", "Visual tuning", "Visual tuning", "Visual tuning"}},
        {"aim.trigger_title", {"Disparo automático", "Trigger", "Trigger", "Trigger", "Trigger", "Trigger"}},
        {"aim.trigger", {"Ativar disparo automático", "Enable Trigger", "Enable Trigger", "Enable Trigger", "Enable Trigger", "Enable Trigger"}},
        {"aim.trigger_fov", {"Exibir FOV do disparo automático", "Show Trigger FOV", "Show Trigger FOV", "Show Trigger FOV", "Show Trigger FOV", "Show Trigger FOV"}},
        {"aim.devices", {"DISPOSITIVOS", "DEVICES", "DEVICES", "DEVICES", "DEVICES", "DEVICES"}},
        {"aim.bind", {"Tecla principal da mira", "Aimbot Bind", "Aimbot Bind", "Aimbot Bind", "Aimbot Bind", "Aimbot Bind"}},
        {"aim.bind2", {"Tecla secundária da mira", "Aimbot Bind [2]", "Aimbot Bind [2]", "Aimbot Bind [2]", "Aimbot Bind [2]", "Aimbot Bind [2]"}},
        {"aim.trigger_hint", {"Dispara automaticamente (Makcu) quando o alvo esta no centro da mira.", "Auto-fires via Makcu when the target is under the crosshair.", "Auto-fires via Makcu when the target is under the crosshair.", "Auto-fires via Makcu when the target is under the crosshair.", "Auto-fires via Makcu when the target is under the crosshair.", "Auto-fires via Makcu when the target is under the crosshair."}},
        {"aim.kmbox_net", {"Usar Kmbox-Net", "Use Kmbox-Net", "Use Kmbox-Net", "Use Kmbox-Net", "Use Kmbox-Net", "Use Kmbox-Net"}},
        {"aim.ferrum", {"Usar Ferrum / Kmbox B+", "Use Ferrum / Kmbox B+", "Use Ferrum / Kmbox B+", "Use Ferrum / Kmbox B+", "Use Ferrum / Kmbox B+", "Use Ferrum / Kmbox B+"}},
        {"aim.makcu", {"Usar Makcu", "Use Makcu", "Use Makcu", "Use Makcu", "Use Makcu", "Use Makcu"}},
        {"aim.ip", {"IP", "IP", "IP", "IP", "IP", "IP"}},
        {"aim.port", {"Porta", "Port", "Port", "Port", "Port", "Port"}},
        {"aim.uuid", {"UUID", "UUID", "UUID", "UUID", "UUID", "UUID"}},
        {"aim.com_port", {"Porta COM", "COM Port", "COM Port", "COM Port", "COM Port", "COM Port"}},
        {"aim.baud", {"Velocidade de transmissão", "Baud Rate", "Baud Rate", "Baud Rate", "Baud Rate", "Baud Rate"}},
        {"aim.bone_head", {"Cabeça", "Head", "Head", "Head", "Head", "Head"}},
        {"aim.bone_neck", {"Pescoço", "Neck", "Neck", "Neck", "Neck", "Neck"}},
        {"aim.bone_chest", {"Peito", "Chest", "Chest", "Chest", "Chest", "Chest"}},
        {"aim.bone_pelvis", {"Pelve", "Pelvis", "Pelvis", "Pelvis", "Pelvis", "Pelvis"}},
        {"aim.fov_circle", {"Circulo", "Circle", "Circle", "Circle", "Circle", "Circle"}},
        {"aim.fov_square", {"Quadrado", "Square", "Square", "Square", "Square", "Square"}},
        {"aim.fov_cross", {"Cruz", "Cross", "Cross", "Cross", "Cross", "Cross"}},
        {"veh.configs", {"DEFINIÇÕES DO VEÍCULO", "VEHICLE CONFIGS", "VEHICLE CONFIGS", "VEHICLE CONFIGS", "VEHICLE CONFIGS", "VEHICLE CONFIGS"}},
        {"veh.customize", {"PERSONALIZACAO", "CUSTOMIZE", "CUSTOMIZE", "CUSTOMIZE", "CUSTOMIZE", "CUSTOMIZE"}},
        {"veh.status", {"ESTADO DO VEICULO", "VEHICLE STATUS", "VEHICLE STATUS", "VEHICLE STATUS", "VEHICLE STATUS", "VEHICLE STATUS"}},
        {"veh.enabled", {"Ativar ESP", "Enable ESP", "Enable ESP", "Enable ESP", "Enable ESP", "Enable ESP"}},
        {"veh.self", {"ESP Proprio", "Self Vehicle", "Self Vehicle", "Self Vehicle", "Self Vehicle", "Self Vehicle"}},
        {"veh.anti_fall", {"Moto Anti-queda", "Anti-Fall Bike", "Anti-Fall Bike", "Anti-Fall Bike", "Anti-Fall Bike", "Anti-Fall Bike"}},
        {"veh.box3d", {"Caixa 3D", "3D Box", "3D Box", "3D Box", "3D Box", "3D Box"}},
        {"veh.snaplines", {"Linhas Guia", "Snaplines", "Snaplines", "Snaplines", "Snaplines", "Snaplines"}},
        {"veh.marker", {"Marcador", "Marker", "Marker", "Marker", "Marker", "Marker"}},
        {"veh.distance", {"Distância", "Distance", "Distanz", "Distancia", "Distance", "Distanza"}},
        {"veh.occupants", {"Mostrar Ocupantes", "Show Occupants", "Show Occupants", "Show Occupants", "Show Occupants", "Show Occupants"}},
        {"veh.name", {"Nome do veículo", "Vehicle Name", "Vehicle Name", "Vehicle Name", "Vehicle Name", "Vehicle Name"}},
        {"veh.ignore_occ", {"Ignorar Ocupado", "Ignore Occupied", "Ignore Occupied", "Ignore Occupied", "Ignore Occupied", "Ignore Occupied"}},
        {"veh.lock_status", {"Estado da fechadura", "Lock Status", "Lock Status", "Lock Status", "Lock Status", "Lock Status"}},
        {"veh.max_dist", {"Distância máxima do ESP", "Max ESP Distance", "Max ESP Distance", "Max ESP Distance", "Max ESP Distance", "Max ESP Distance"}},
        {"veh.actions", {"Acoes", "Actions", "Actions", "Actions", "Actions", "Actions"}},
        {"veh.unlock", {"Destrancar Veiculo", "Unlock Vehicle", "Unlock Vehicle", "Unlock Vehicle", "Unlock Vehicle", "Unlock Vehicle"}},
        {"veh.lock", {"Trancar Veiculo", "Lock Vehicle", "Lock Vehicle", "Lock Vehicle", "Lock Vehicle", "Lock Vehicle"}},
        {"veh.fix", {"Reparacao Total", "Full Repair", "Full Repair", "Full Repair", "Full Repair", "Full Repair"}},
        {"veh.fix_motor", {"Reparacao Moto", "Engine Repair", "Engine Repair", "Engine Repair", "Engine Repair", "Engine Repair"}},
        {"veh.rgb", {"Modo RGB", "RGB Mode", "RGB Mode", "RGB Mode", "RGB Mode", "RGB Mode"}},
        {"veh.snap_pos", {"Posicao Linhas Guia", "Snapline Position", "Snapline Position", "Snapline Position", "Snapline Position", "Snapline Position"}},
        {"veh.color_box", {"Caixa 3D", "3D Box", "3D Box", "3D Box", "3D Box", "3D Box"}},
        {"veh.color_snap", {"Linhas Guia", "Snaplines", "Snaplines", "Snaplines", "Snaplines", "Snaplines"}},
        {"veh.color_marker", {"Marcador", "Marker", "Marker", "Marker", "Marker", "Marker"}},
        {"veh.color_dist", {"Distância", "Distance", "Distanz", "Distancia", "Distance", "Distanza"}},
        {"veh.color_unlock", {"Estado destrancado", "Unlocked Status", "Unlocked Status", "Unlocked Status", "Unlocked Status", "Unlocked Status"}},
        {"veh.color_lock", {"Estado trancado", "Locked Status", "Locked Status", "Locked Status", "Locked Status", "Locked Status"}},
        {"veh.color_occ", {"Ocupantes", "Occupants", "Occupants", "Occupants", "Occupants", "Occupants"}},
        {"veh.color_name", {"Nome do veículo", "Vehicle Name", "Vehicle Name", "Vehicle Name", "Vehicle Name", "Vehicle Name"}},
        {"veh.st_box", {"CAIXA 3D", "BOX 3D", "BOX 3D", "BOX 3D", "BOX 3D", "BOX 3D"}},
        {"veh.st_snap", {"LINHAS GUIA", "SNAPLINES", "SNAPLINES", "SNAPLINES", "SNAPLINES", "SNAPLINES"}},
        {"veh.st_occ", {"OCUPANTES", "OCCUPANTS", "OCCUPANTS", "OCCUPANTS", "OCCUPANTS", "OCCUPANTS"}},
        {"veh.st_guide", {"GUIA", "GUIDE", "GUIDE", "GUIDE", "GUIDE", "GUIDE"}},
        {"veh.st_range", {"ALCANCE MAX", "MAX RANGE", "MAX RANGE", "MAX RANGE", "MAX RANGE", "MAX RANGE"}},
        {"fr.list", {"LISTA DE AMIGOS", "FRIEND LIST", "FRIEND LIST", "FRIEND LIST", "FRIEND LIST", "FRIEND LIST"}},
        {"fr.players", {"JOGADORES", "PLAYERS", "PLAYERS", "PLAYERS", "PLAYERS", "PLAYERS"}},
        {"fr.nearby", {"Jogadores proximos: %d", "Nearby players: %d", "Nearby players: %d", "Nearby players: %d", "Nearby players: %d", "Nearby players: %d"}},
        {"fr.ignore_aim", {"Ignorar amigos na mira", "Ignore Friends in Aim", "Ignore Friends in Aim", "Ignore Friends in Aim", "Ignore Friends in Aim", "Ignore Friends in Aim"}},
        {"fr.ignore_silent", {"Ignorar amigos na mira silenciosa", "Ignore Friends in Silent", "Ignore Friends in Silent", "Ignore Friends in Silent", "Ignore Friends in Silent", "Ignore Friends in Silent"}},
        {"fr.show_esp", {"Exibir ESP Amigo", "Show Friend ESP", "Show Friend ESP", "Show Friend ESP", "Show Friend ESP", "Show Friend ESP"}},
        {"fr.color", {"Cor do Amigo", "Friend Color", "Friend Color", "Friend Color", "Friend Color", "Friend Color"}},
        {"fr.add_prox", {"Adicionar por Prox.", "Add by Proximity", "Add by Proximity", "Add by Proximity", "Add by Proximity", "Add by Proximity"}},
        {"fr.prox_dist", {"Distância máxima", "Max Distance", "Max Distance", "Max Distance", "Max Distance", "Max Distance"}},
        {"fr.add_closest", {"Adicionar proximo", "Add closest", "Add closest", "Add closest", "Add closest", "Add closest"}},
        {"fr.remove_closest", {"Remover proximo", "Remove closest", "Remove closest", "Remove closest", "Remove closest", "Remove closest"}},
        {"fr.count", {"Amigos (%d)", "Friends (%d)", "Friends (%d)", "Friends (%d)", "Friends (%d)", "Friends (%d)"}},
        {"fr.empty", {"Nenhum amigo adicionado", "No friends added", "No friends added", "No friends added", "No friends added", "No friends added"}},
        {"fr.empty_hint", {"Usa Adicionar proximo ou a lista de jogadores.", "Use Add closest or the players list.", "Use Add closest or the players list.", "Use Add closest or the players list.", "Use Add closest or the players list.", "Use Add closest or the players list."}},
        {"fr.search", {"Procurar", "Search", "Suchen", "Buscar", "Rechercher", "Cerca"}},
        {"fr.search_hint", {"Filtrar jogadores...", "Filter players...", "Filter players...", "Filter players...", "Filter players...", "Filter players..."}},
        {"fr.add_selected", {"Adicionar Prox", "Add Closest", "Add Closest", "Add Closest", "Add Closest", "Add Closest"}},
        {"cfg.visual", {"VISUAL", "VISUAL", "VISUAL", "VISUAL", "VISUAL", "VISUAL"}},
        {"cfg.settings", {"DEFINICOES", "SETTINGS", "SETTINGS", "SETTINGS", "SETTINGS", "SETTINGS"}},
        {"cfg.black_bg", {"Fundo Preto", "Black Background", "Black Background", "Black Background", "Black Background", "Black Background"}},
        {"cfg.perf", {"Modo de desempenho", "Performance Mode", "Leistungsmodus", "Modo Rendimiento", "Mode Performance", "Modalita Performance"}},
        {"cfg.particles", {"Particulas", "Particles", "Particles", "Particles", "Particles", "Particles"}},
        {"cfg.snow", {"Efeito Floco de Neve", "Snow Effect", "Snow Effect", "Snow Effect", "Snow Effect", "Snow Effect"}},
        {"cfg.matrix", {"Chuva digital (fundo)", "Matrix Rain (background)", "Matrix Rain (background)", "Matrix Rain (background)", "Matrix Rain (background)", "Matrix Rain (background)"}},
        {"cfg.matrix_hint", {"Chuva digital dourada no fundo da interface.", "Golden digital rain in the background.", "Golden digital rain in the background.", "Golden digital rain in the background.", "Golden digital rain in the background.", "Golden digital rain in the background."}},
        {"cfg.show_fps", {"Exibir FPS", "Show FPS", "FPS anzeigen", "Mostrar FPS", "Afficher FPS", "Mostra FPS"}},
        {"cfg.vsync", {"Ativar V-Sync", "Enable V-Sync", "Enable V-Sync", "Enable V-Sync", "Enable V-Sync", "Enable V-Sync"}},
        {"cfg.colors", {"Cores", "Colors", "Colors", "Colors", "Colors", "Colors"}},
        {"cfg.color_primary", {"Botao Primario", "Primary Button", "Primary Button", "Primary Button", "Primary Button", "Primary Button"}},
        {"cfg.color_secondary", {"Botao Secundario", "Secondary Button", "Secondary Button", "Secondary Button", "Secondary Button", "Secondary Button"}},
        {"cfg.color_fps", {"Indicador de FPS", "FPS Display", "FPS Display", "FPS Display", "FPS Display", "FPS Display"}},
        {"cfg.color_particles", {"Particulas", "Particles", "Particles", "Particles", "Particles", "Particles"}},
        {"cfg.theme", {"Tema da Interface", "Interface Theme", "Interface Theme", "Interface Theme", "Interface Theme", "Interface Theme"}},
        {"cfg.language", {"Idioma", "Language", "Sprache", "Idioma", "Langue", "Lingua"}},
        {"cfg.menu_bind", {"Tecla para abrir o menu", "Open Menu Bind", "Open Menu Bind", "Open Menu Bind", "Open Menu Bind", "Open Menu Bind"}},
        {"cfg.rebind", {"ALTERAR TECLA DO MENU", "REBIND MENU KEY", "REBIND MENU KEY", "REBIND MENU KEY", "REBIND MENU KEY", "REBIND MENU KEY"}},
        {"cfg.reset_insert", {"REPOR TECLA INSERT", "RESET INSERT KEY", "RESET INSERT KEY", "RESET INSERT KEY", "RESET INSERT KEY", "RESET INSERT KEY"}},
        {"cfg.aura50", {"50% Modo Aura", "50% Aura Mode", "50% Aura Mode", "50% Aura Mode", "50% Aura Mode", "50% Aura Mode"}},
        {"cfg.aura100", {"100% Modo Aura", "100% Aura Mode", "100% Aura Mode", "100% Aura Mode", "100% Aura Mode", "100% Aura Mode"}},
        {"save.title", {"GUARDAR / CARREGAR", "SAVE / LOAD", "SAVE / LOAD", "SAVE / LOAD", "SAVE / LOAD", "SAVE / LOAD"}},
        {"save.list", {"CONFIGURAÇÕES GUARDADAS", "SAVED CONFIGS", "SAVED CONFIGS", "SAVED CONFIGS", "SAVED CONFIGS", "SAVED CONFIGS"}},
        {"save.create", {"Criar configuração", "Create Config", "Config erstellen", "Crear Config", "Creer Config", "Crea Config"}},
        {"save.open_folder", {"Abrir Pasta", "Open Folder", "Ordner offnen", "Abrir Carpeta", "Ouvrir Dossier", "Apri Cartella"}},
        {"save.copy", {"Copiar para a área de transferência", "Copy Clipboard", "Copy Clipboard", "Copy Clipboard", "Copy Clipboard", "Copy Clipboard"}},
        {"save.paste", {"Colar da área de transferência", "Paste Clipboard", "Paste Clipboard", "Paste Clipboard", "Paste Clipboard", "Paste Clipboard"}},
        {"save.reset", {"Repor Padrao", "Reset Defaults", "Standard", "Restablecer", "Reinitialiser", "Predefiniti"}},
    };

    const char* Pick(const Pack& pack)
    {
        using app_settings::Language;
        switch (app_settings::config.language) {
        case Language::PT: return pack.pt && pack.pt[0] ? pack.pt : pack.en;
        case Language::EN: return pack.en && pack.en[0] ? pack.en : pack.pt;
        case Language::DE: return pack.de && pack.de[0] ? pack.de : pack.en;
        case Language::ES: return pack.es && pack.es[0] ? pack.es : pack.en;
        case Language::FR: return pack.fr && pack.fr[0] ? pack.fr : pack.en;
        case Language::IT: return pack.it && pack.it[0] ? pack.it : pack.en;
        default:           return pack.en ? pack.en : pack.pt;
        }
    }

} // namespace

    const char* Tr(const char* key)
    {
        if (!key || !key[0])
            return "";
        const auto it = kTable.find(key);
        if (it == kTable.end())
            return key;
        const char* value = Pick(it->second);
        return (value && value[0]) ? value : key;
    }

    const char* TrID(const char* key)
    {
        constexpr int kBuffers = 64;
        constexpr int kSize = 192;
        static thread_local char buffers[kBuffers][kSize];
        static thread_local int index = 0;
        char* buf = buffers[index];
        index = (index + 1) % kBuffers;
        const char* text = Tr(key);
        std::snprintf(buf, kSize, "%s###%s", text ? text : key, key);
        return buf;
    }

    const char* LanguageName(int index)
    {
        static const char* names[] = { "Português", "English", "Deutsch", "Español", "Français", "Italiano" };
        if (index < 0 || index >= 6)
            return names[0];
        return names[index];
    }

    int LanguageCount()
    {
        return 6;
    }

} // namespace Loc
