[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][string]$CertificateThumbprint,
    [Parameter(Mandatory=$false)][string]$SecondaryCertificateThumbprint = '',
    [Parameter(Mandatory=$false)][string]$ProjectDir = (Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)),
    [ValidateSet('CurrentUser','LocalMachine')][string]$StoreLocation = 'CurrentUser'
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$ProjectDir = [IO.Path]::GetFullPath($ProjectDir)
$thumb = ($CertificateThumbprint -replace '\s','').ToUpperInvariant()
if ($thumb -notmatch '^[0-9A-F]{40}$') { throw 'Certificate thumbprint must be a 40-character SHA-1 thumbprint.' }
$storePath = "Cert:\$StoreLocation\My\$thumb"
$cert = Get-Item -LiteralPath $storePath -ErrorAction Stop
if (-not $cert.HasPrivateKey) { throw "The certificate at $storePath has no private key. Configure trust from the release/signing environment." }
if ($cert.NotAfter.ToUniversalTime() -le [DateTime]::UtcNow) { throw 'The signing certificate is expired.' }

$subject = [string]$cert.Subject
$der = [Convert]::ToBase64String($cert.RawData)
$secondarySubject = ''
$secondaryThumb = ''
$secondaryDer = ''
$secondaryConfigured = 'false'
if (-not [string]::IsNullOrWhiteSpace($SecondaryCertificateThumbprint)) {
    $secondaryThumb = ($SecondaryCertificateThumbprint -replace '\s','').ToUpperInvariant()
    if ($secondaryThumb -notmatch '^[0-9A-F]{40}$') { throw 'Secondary certificate thumbprint must be a 40-character SHA-1 thumbprint.' }
    if ($secondaryThumb -ceq $thumb) { throw 'Primary and secondary release certificates must be different.' }
    $secondaryCert = Get-Item -LiteralPath "Cert:\$StoreLocation\My\$secondaryThumb" -ErrorAction Stop
    if ($secondaryCert.NotAfter.ToUniversalTime() -le [DateTime]::UtcNow) { throw 'The secondary signing certificate is expired.' }
    $secondarySubject = [string]$secondaryCert.Subject
    $secondaryDer = [Convert]::ToBase64String($secondaryCert.RawData)
    $secondaryConfigured = 'true'
}
function Escape-Cpp([string]$v) { return $v.Replace('\\','\\\\').Replace('"','\\"') }
$header = @"
#pragma once

// Generated by tools/Configure-ReleaseTrust.ps1.
// PUBLIC certificate only. The private key remains in the Windows certificate store.
namespace OmniGhost::Update::ReleaseTrust {
inline constexpr char PublisherSubject[] = "$(Escape-Cpp $subject)";
inline constexpr char CertificateThumbprint[] = "$thumb";
inline constexpr char PublicCertificateDerBase64[] = "$der";
inline constexpr char SecondaryPublisherSubject[] = "$(Escape-Cpp $secondarySubject)";
inline constexpr char SecondaryCertificateThumbprint[] = "$secondaryThumb";
inline constexpr char SecondaryPublicCertificateDerBase64[] = "$secondaryDer";
inline constexpr bool Configured = true;
inline constexpr bool SecondaryConfigured = $secondaryConfigured;
}
"@
$utf8 = New-Object System.Text.UTF8Encoding($false)
$headerPath = Join-Path $ProjectDir 'src\updater\release_trust.h'
[IO.File]::WriteAllText($headerPath, $header.TrimStart() + [Environment]::NewLine, $utf8)

$configPath = Join-Path $ProjectDir 'release-publish.json'
if (Test-Path -LiteralPath $configPath) {
    $config = Get-Content -LiteralPath $configPath -Raw | ConvertFrom-Json
    $config.signingCertificateThumbprint = $thumb
    $config.expectedPublisherSubject = $subject
    $config.secondarySigningCertificateThumbprint = $secondaryThumb
    $config.secondaryExpectedPublisherSubject = $secondarySubject
    $json = ($config | ConvertTo-Json -Depth 8) + [Environment]::NewLine
    [IO.File]::WriteAllText($configPath, $json, $utf8)
}
Write-Host "[OmniGhost Trust] Publisher: $subject"
Write-Host "[OmniGhost Trust] Thumbprint: $thumb"
Write-Host "[OmniGhost Trust] Expires (UTC): $($cert.NotAfter.ToUniversalTime().ToString('o'))"
if ($secondaryConfigured -eq 'true') {
    Write-Host "[OmniGhost Trust] Secondary rotation thumbprint: $secondaryThumb"
}
Write-Host "[OmniGhost Trust] Public certificate embedded in src\updater\release_trust.h"
Write-Host '[OmniGhost Trust] No private key was written to the project.'
